---
- name: Update all packages
    yum:
      name: '*'
      state: latest
        update_cache: yes

- name: Install wget package
    yum:
     name: wget
        state: present
- name: Install java-17-openjdk package
    yum:
      name: java-17-openjdk
      state: present

- name: Create /app directory
    file:
      path: /app
      state: directory
      mode: '0755'

- name: List files in /app
    command: ls
      args:
        chdir: /app


- name: Fetch Nexus download page
    uri:
      url: "https://www.sonatype.com/download-nexus-repository"
      return_content: yes
    register: nexus_download_page


- name: Extract Nexus tarball to /app
    unarchive:
      src: /app/nexus.tar.gz  # Path to the tar.gz file
      dest: /app              # Destination directory for extraction
      remote_src: yes         # The file is already on the remote machine
      creates: /app/nexus-3* 

- name: Rename the extracted directory to 'nexus'
    command: mv /app/nexus-3* /app/nexus

- name: Add the 'nexus' user
    user:
      name: nexus        # User name to create
      state: present     # Ensures the user is created
      shell: /bin/bash   # Optional: Set the default shell (default is /bin/bash)
      comment: "Nexus User for Nexus Repository" 

- name: Change ownership of /app/nexus to nexus:nexus
    file:
      path: /app/nexus          # Path to the directory
      owner: nexus              # Set the owner to 'nexus'
      group: nexus              # Set the group to 'nexus'
      recurse: yes              # Apply recursively to all files and subdirectories

- name: Change ownership of /app/sonatype-work to nexus:nexus
    file:
      path: /app/sonatype-work  # Path to the directory
      owner: nexus              # Set the owner to 'nexus'
      group: nexus              # Set the group to 'nexus'
      recurse: yes              # Apply recursively to all files and subdirectories
- name: Ensure run_as_user is set to 'nexus' in /app/nexus/bin/nexus.rc
    lineinfile:
      path: /app/nexus/bin/nexus.rc  # Path to the file
      regexp: '^run_as_user='         # Search for the line starting with 'run_as_user='
      line: 'run_as_user="nexus"'     # Set the line to 'run_as_user="nexus"'
      create: yes      
- name: Copy the nexus.service file to /etc/systemd/system/
    copy:
      src: files/nexus.service  # Path to the file on the Ansible control machine
      dest: /etc/systemd/system/nexus.service  # Destination path on the target machine
      owner: nexus
      group: nexus
      mode: '0644'



- name: Enable nexus service to start on boot using chkconfig
    command: chkconfig nexus on
    notify:
      - Reload systemd
      - Enable and start Nexus